- JSONModel/JSONModel/JSONModel.m
Consider an example model:
```objc
@interface MyRootObject : JSONModel
@property (strong, nonatomic) MyRootMetadata* metadata;
@end
@interface MySpecificObject : MyRootObject
@property (strong, nonatomic) MySpecificMetadata* metadata;
@end
```
And the metadata classes look like:
```objc
@interface MyRootMetadata : JSONModel
// ...
@end
@interface MySpecificMetadata: MyRootMetadata
// ...
@end
```
Essentially `MySpecificObject` has overridden its `metadata` property to be of a more specific class type. The JSONModel parser prefers to get property name/information from the most root class, rather than the most specific class.
This fix gives priority to the specific class over the root class.
> Store property type information from most specific class instead of most generic class

- JSONModel/JSONModel/JSONModelArray.h
- JSONModel/JSONModel/JSONModelArray.m
- JSONModelDemoTests/UnitTests/ArrayTests.m
Bring back fast enumeration to JSONModelArray, lost in commit c4ffee63b64a71c1319b6b5149f60ee88c5f92b8. Based on a [sample from Apple](https://developer.apple.com/library/mac/samplecode/FastEnumerationSample/Introduction/Intro.html#//apple_ref/doc/uid/DTS40009411-Intro-DontLinkElementID_2).
> Bring back fast enumeration to JSONModelArray

- JSONModel/JSONModelTransformations/JSONValueTransformer.m
I've confirmed the fix with users.
In certain locales, or perhaps for people that travel, saving and loading is inconsistent and loads as either nil or 01-01-2001. 
If a locale isn't specified on the save, I believe iOS uses whatever locale is currently set. If that changes, this can cause problems.
The locale needs to be forced on read and write to have data consistency.
> Fixed read/write issue for certain locales.

- JSONModel/JSONModel/JSONModel.h
This pull request fixes a minor typo in the JSONModel.h header documentation.
> Fixing typo in JSONModel header documentation.

- JSONModel/JSONModel/JSONModel.m
Add error log in initWithCoder.
When I use [NSKeyedArchiver archiveRootObject] selector to serialize my model which is subclass of JSONModel,it is ok.But When I use [NSKeyedUnarchiver unarchiveObjectWithFile] to unserialize it,it just don't work and It makes me some time to figure out the property must be optional if it can be nil because there is no any log.
> Add error log in initWithCoder.

- JSONModel/JSONModelTransformations/JSONValueTransformer.m
e.g. this will handle white spaces in string (convert to %20) instead of returning a nil object.
> Safer transformation of NSURLFromNSString

- JSONModel/JSONModel/JSONModel.m
The requiredPropertyNames are stored as an associated object on the class, but during initialization that mutable set can be modified.
This change creates a mutableCopy of the requiredProperties, which allows concurrent changes to the requiredProperties.
> Fix bug in modifying the shared requiredPropertyNames of a JSONModel

- JSONModel/JSONModel/JSONModel.h
- JSONModel/JSONModel/JSONModel.m
- JSONModelDemoTests/UnitTests/ArrayTests.m
- JSONModelDemoTests/UnitTests/TestModels/ReposModel.h
- JSONModelDemoTests/UnitTests/TestModels/ReposModel.m
Rather than declaring the contained type of an NSArray property like:
```objc
@property (strong) NSArray<MyType>* things;
```
You can alternatively implement the `+protocolForArrayProperty:` method:
```objc
+ (NSString*)protocolForArrayProperty:(NSString*)propertyName
{
if ([propertyName isEqualToString:NSStringFromSelector(@selector(things))]) {
return NSStringFromClass(MyType.class);
}
return [super protocolForArrayProperty:propertyName];
}
```
We use JSONModel to define classes for our public API. I would prefer to not leak JSONModel implementation details through our API's public surface area. Non-standard use of protocols is one of those leaks. By allowing you to alternatively choose the container type for NSArray property in the implementation of your class, we can hide these …
> Allow specifying an NSArray's protocol type in implementation method

- JSONModel/JSONModelTransformations/JSONKeyMapper.m
I found a very shocking line in this code. 
```
NSMutableDictionary* userToJSONMap  = [NSMutableDictionary dictionaryWithObjects:map.allKeys forKeys:map.allValues];
```
Reading the documentation it is clear that this was working by pure luck:
```
@property(readonly, copy) NSArray *allKeys
Description	
A new array containing the dictionary’s keys, or an empty array if the dictionary has no entries (read-only)
The order of the elements in the array is not defined.
@property(readonly, copy) NSArray *allValues
Description	
A new array containing the dictionary’s values, or an empty array if the dictionary has no entries (read-only)
The order of the values in the array isn’t defined.
```
> Fixing very unsafe code

- JSONModel.podspec
Allows JSONModel to be included in via CocoaPods into a watchOS 2 project.
> Add deployment target to support watchOS 2

- JSONModel/JSONModel/JSONModel.m
- JSONModel/JSONModel/JSONModelClassProperty.h
- JSONModel/JSONModel/JSONModelClassProperty.m
The existing behavior is flawed in that the first custom setter used would always be used, even for values of a different type. This new behavior caches the setter on a per-type basis.
Resolves #345
> Allow custom setters for multiple types

- JSONModel/JSONModel/JSONModelError.h
- JSONModel/JSONModelNetworking/JSONHTTPClient.m
I have a situation where my API returns error information (some text) in the response.
To be able to retrieve that, I added the `responseData` in `JSONModelError`. That way I can do this:
if (error) {
NSString* errorInfo = [[NSString alloc] initWithData:error.responseData 
encoding:NSUTF8StringEncoding];
...
}
> Keep responseData in JSONModelError

- JSONModel.podspec
This will solve an issue with AFNetworking integration using it as a dependency on a third library.
For example, I created a library that depends on JSONModel v1.1.0 and AFNetworking v2.6.0 but it doesn't compile if JSONModel declare an iOS compatibility as iOS >= 5.0
> Updated iOS deplyoment target

- JSONModel/JSONModelNetworking/JSONAPI.h
- JSONModel/JSONModelNetworking/JSONAPI.m
- JSONModel/JSONModelNetworking/JSONHTTPClient.h
- JSONModel/JSONModelNetworking/JSONHTTPClient.m
- JSONModel/JSONModelNetworking/JSONModel+networking.h
- JSONModelDemoTests/UnitTests/HTTPClientSuite.m
- JSONModelDemoTests/UnitTests/InitFromWebTests.m
- JSONModelDemoTests/UnitTests/JSONAPITests.m
- JSONModelDemo_iOS/KivaViewController.m
- JSONModelDemo_iOS/KivaViewControllerNetworking.m
- JSONModelOSX/ViewController.m
As discussed in #497. This deprecates all the JSONModelNetworking code.
> Deprecate networking support

- JSONModel/JSONModel/JSONModel.h
- JSONModelDemoTests/UnitTests/KeyMappingTests.m
As discussed in #497. This deprecates the `+setGlobalKeyMapper:` method.
This change needs a bit more consideration & discussion before merging I think, but it's available if we do decide to make the change.
> Deprecate global key mapper

- README.md
References to old `icanzilb` repo were changed to `JSONModel`
> Replaced icanzilb for JSONModel

- JSONModel/JSONModel/JSONModel.h
- JSONModel/JSONModel/JSONModel.m
- JSONModel/JSONModel/JSONModelClassProperty.h
- JSONModel/JSONModel/JSONModelClassProperty.m
- JSONModelDemoTests/UnitTests/TestModels/GitHubKeyMapRepoModel.h
- JSONModelDemoTests/UnitTests/TestModels/GitHubRepoModel.h
- JSONModelDemoTests/UnitTests/TestModels/PostModel.h
As discussed in #497. This deprecates the `Index` protocol.
> Deprecate `Index` protocol

- JSONModel/JSONModel/JSONModel.m
Hey,
This is just a tiny improvement. We should use more secure way how to decode object when it's available.
Vojta
> Use NSSecureCoding instead of NSCoding when possible

- JSONModel.xcodeproj/project.pbxproj
Change access target access of `JSONModelClassProperty.h` file from `Public` to `Project`. Without this change installing `JSONModel` with `Carthage` will raise error 
> Umbrella header for module 'JSONModel' does not include header 'JSONModelClassProperty.h'
> Change access control of JSONModelClassProperty header to internal

- Examples/Examples.xcodeproj/project.pbxproj
- Examples/Tests/ConcurrentTests.m
- Examples/Tests/Models/Headers/ConcurrentReposModel.h
- Examples/Tests/Models/Headers/ConcurrentReposModel.m
- JSONModel/JSONModel/JSONModel.m
- JSONModel/JSONModel/JSONModelClassProperty.h
Fix crash by moving custom setter name generation to ```__inspectProperties__``` method.
@billinghamj Do you have unit test cases I can run with? to check the fix won't break other parts.
> Fix custom setter dictionary crash when multithreading(#436)

- Examples/Tests/Data/primitives.json
- Examples/Tests/Data/primitivesWithErrors.json
- Examples/Tests/Models/Headers/PrimitivesModel.h
- Examples/Tests/PrimitiveTypesReadTests.m
- JSONModel/JSONModel/JSONModel.m
- JSONModel/JSONModelTransformations/JSONValueTransformer.m
support more like unsigned int , unsigned short etc...
> add more primitive types support

- JSONModel.xcodeproj/project.pbxproj
In #482 a module map file was added that fixed an issue when installing
JSONModel with Carthage. But it seems to me that the fix was only applied
to the iOS target (or maybe the other targets were only added later?),
which means I can still see the issue when trying to install on macOS:
<module-includes>:1:1: error: umbrella header for module 'JSONModel' does not include header 'JSONAPI.h' [-Werror,-Wincomplete-umbrella]
#import "Headers/JSONModel.h"
^
<module-includes>:1:1: error: umbrella header for module 'JSONModel' does not include header 'JSONHTTPClient.h' [-Werror,-Wincomplete-umbre
<module-includes>:1:1: error: umbrella header for module 'JSONModel' does not include header 'JSONModel+networking.h' [-Werror,-Wincomplete
<module-includes>:1:1: error: umbrella header for module …
> Add module map file to targets other than iOS
